title: ""
author: ""
description: "Plataforma de evaluación y seguimiento académico"
permalink: /:collection/:title/
lang: "es"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# --- MODIFICACIONES PARA EL DASHBOARD ---

# Desactivamos el modo blog minimalista
show_excerpts: false           
show_frame: true                
show_sidebar: true            # Cambiado a false para usar el layout de UIkit completo
show_minimal: false            # Desactivado para permitir mayor libertad de diseño

# Definición de la nueva estructura
collections:
  materias:
    output: true

# Navigation actualizada para tu Escuela
navigation:
  - {file: "index.html", title: "Dashboard", sidebaricon: home}
  - {file: "materias.html", title: "Materias", sidebaricon: book}

# Mantén tus enlaces externos preferidos
external:
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}

plugins:
 - jekyll-feed
